export const mockUsers = [
  {
    id: "1",
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+44 7700 900123",
    address: "123 High Street, London, SW1A 1AA",
    package: "Popular",
    status: "Active",
    joinDate: "2023-08-15",
    lastPayment: "2024-01-15",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    phone: "+44 7700 900124",
    address: "456 Oak Avenue, Manchester, M1 2AB",
    package: "Essential",
    status: "Active",
    joinDate: "2023-09-20",
    lastPayment: "2024-01-10",
  },
  {
    id: "3",
    name: "Mike Chen",
    email: "mike.chen@email.com",
    phone: "+44 7700 900125",
    address: "789 Pine Road, Birmingham, B1 3CD",
    package: "Superfast",
    status: "Suspended",
    joinDate: "2023-07-10",
    lastPayment: "2023-12-15",
  },
  {
    id: "4",
    name: "Emma Williams",
    email: "emma.williams@email.com",
    phone: "+44 7700 900126",
    address: "321 Elm Street, Leeds, LS1 4EF",
    package: "Ultrafast",
    status: "Active",
    joinDate: "2023-10-05",
    lastPayment: "2024-01-12",
  },
]

export const mockPackages = [
  {
    id: "1",
    name: "Essential",
    speed: "50 Mbps",
    price: 25,
    description: "Perfect for browsing and streaming",
    features: ["Unlimited data", "Free router", "24/7 support"],
    status: "Active",
    subscribers: 1250,
  },
  {
    id: "2",
    name: "Popular",
    speed: "150 Mbps",
    price: 35,
    description: "Great for families and home working",
    features: ["Unlimited data", "Wi-Fi 6 router", "24/7 support", "Parental controls"],
    status: "Active",
    subscribers: 2840,
  },
  {
    id: "3",
    name: "Superfast",
    speed: "500 Mbps",
    price: 45,
    description: "Ultimate performance for power users",
    features: ["Unlimited data", "Premium router", "Priority support", "Security suite"],
    status: "Active",
    subscribers: 1680,
  },
  {
    id: "4",
    name: "Ultrafast",
    speed: "1 Gbps",
    price: 55,
    description: "Maximum speed for demanding households",
    features: ["Unlimited data", "Premium router", "Priority support", "Business SLA"],
    status: "Active",
    subscribers: 920,
  },
]

export const mockOrders = [
  {
    id: "ORD-001",
    customerName: "John Smith",
    email: "john.smith@email.com",
    package: "Popular",
    amount: 35,
    status: "Completed",
    orderDate: "2024-01-15",
    installationDate: "2024-01-22",
    address: "123 High Street, London, SW1A 1AA",
  },
  {
    id: "ORD-002",
    customerName: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    package: "Essential",
    amount: 25,
    status: "Pending",
    orderDate: "2024-01-14",
    installationDate: "2024-01-25",
    address: "456 Oak Avenue, Manchester, M1 2AB",
  },
  {
    id: "ORD-003",
    customerName: "Mike Chen",
    email: "mike.chen@email.com",
    package: "Superfast",
    amount: 45,
    status: "In Progress",
    orderDate: "2024-01-13",
    installationDate: "2024-01-20",
    address: "789 Pine Road, Birmingham, B1 3CD",
  },
  {
    id: "ORD-004",
    customerName: "Emma Williams",
    email: "emma.williams@email.com",
    package: "Ultrafast",
    amount: 55,
    status: "Completed",
    orderDate: "2024-01-12",
    installationDate: "2024-01-18",
    address: "321 Elm Street, Leeds, LS1 4EF",
  },
]

export const mockContacts = [
  {
    id: "1",
    name: "David Thompson",
    email: "david.thompson@email.com",
    phone: "+44 7700 900127",
    subject: "Installation Query",
    message: "I would like to know more about the installation process and timeline.",
    status: "New",
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    name: "Lisa Brown",
    email: "lisa.brown@email.com",
    phone: "+44 7700 900128",
    subject: "Billing Issue",
    message: "I have a question about my recent bill. The amount seems incorrect.",
    status: "In Progress",
    createdAt: "2024-01-14T14:20:00Z",
  },
  {
    id: "3",
    name: "Robert Wilson",
    email: "robert.wilson@email.com",
    phone: "+44 7700 900129",
    subject: "Technical Support",
    message: "My internet connection has been slow for the past few days.",
    status: "Resolved",
    createdAt: "2024-01-13T09:15:00Z",
  },
  {
    id: "4",
    name: "Jennifer Davis",
    email: "jennifer.davis@email.com",
    phone: "+44 7700 900130",
    subject: "Package Upgrade",
    message: "I'm interested in upgrading to a faster package. What are my options?",
    status: "New",
    createdAt: "2024-01-12T16:45:00Z",
  },
]
